#!/usr/bin/env bash
set -euo pipefail

# Generated by /orchestrate init on 2026-06-17
# Edit by hand when dependencies change, or run: /orchestrate init --refresh-bootstrap

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

echo "==> Starting PostgreSQL via Docker Compose"
if command -v docker >/dev/null 2>&1; then
  docker compose up -d db
else
  echo "WARNING: docker not found — start PostgreSQL manually (db=iaw, user=iaw, pass=iaw, port=5432)"
fi

echo "==> Restoring .NET backend"
if command -v dotnet >/dev/null 2>&1; then
  ( cd src/backend && dotnet restore && dotnet build )
  echo "==> Applying EF Core migrations"
  ( cd src/backend && dotnet ef database update --project IAW.Infrastructure --startup-project IAW.Api ) || echo "migrations skipped (run after first migration is added)"
else
  echo "WARNING: dotnet SDK not found — install .NET 8 SDK"
fi

echo "==> Installing frontend deps"
if command -v npm >/dev/null 2>&1; then
  ( cd src/frontend && npm install )
else
  echo "WARNING: npm not found — install Node 20+"
fi

echo "==> Seeding mock data"
( cd src/backend && dotnet run --project IAW.Api -- --seed ) || echo "seed skipped (available after MVP-0)"

echo "==> Security baseline checks"
( cd src/backend && dotnet list package --vulnerable 2>/dev/null ) || true
( cd src/frontend && npm audit --audit-level=high 2>/dev/null ) || true

echo "Bootstrap complete."
echo "Run backend:  cd src/backend && dotnet run --project IAW.Api"
echo "Run frontend: cd src/frontend && npm run dev"
