// <auto-generated />
using System;
using IAW.Vdf.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IAW.Vdf.Persistence.Migrations
{
    [DbContext(typeof(VdfDbContext))]
    partial class VdfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IAW.Vdf.Persistence.Entities.DecisionTraceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Applied")
                        .HasColumnType("boolean")
                        .HasColumnName("applied");

                    b.Property<bool?>("AssertResult")
                        .HasColumnType("boolean")
                        .HasColumnName("assert_result");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions_json");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("FactsReadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("facts_read_json");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phase");

                    b.Property<string>("ProducedOutcomeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("produced_outcome_json");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("rule_key");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_decision_traces_correlation_id");

                    b.HasIndex("RuleKey")
                        .HasDatabaseName("ix_decision_traces_rule_key");

                    b.ToTable("decision_traces", (string)null);
                });

            modelBuilder.Entity("IAW.Vdf.Persistence.Entities.ReferenceDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("key");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("Id");

                    b.HasIndex("Source", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_reference_data_source_key");

                    b.ToTable("reference_data", (string)null);
                });

            modelBuilder.Entity("IAW.Vdf.Persistence.Entities.RuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phase");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("rule_key");

                    b.Property<string>("RuleSet")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("rule_set");

                    b.HasKey("Id");

                    b.HasIndex("RuleKey")
                        .IsUnique()
                        .HasDatabaseName("ix_rules_rule_key");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("IAW.Vdf.Persistence.Entities.RuleVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("approved_by");

                    b.Property<string>("AuthorNl")
                        .HasColumnType("text")
                        .HasColumnName("author_nl");

                    b.Property<string>("AuthoredBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasDefaultValue("system")
                        .HasColumnName("authored_by");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_json");

                    b.Property<DateTimeOffset>("EffectiveDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("effective_date");

                    b.Property<DateTimeOffset?>("ExpiryDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expiry_date");

                    b.Property<string>("InterpreterVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("interpreter_version");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "EffectiveDate")
                        .HasDatabaseName("ix_rule_versions_is_active_effective_date");

                    b.HasIndex("RuleId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_rule_versions_rule_id_version");

                    b.ToTable("rule_versions", (string)null);
                });

            modelBuilder.Entity("IAW.Vdf.Persistence.Entities.RuleVersionEntity", b =>
                {
                    b.HasOne("IAW.Vdf.Persistence.Entities.RuleEntity", "Rule")
                        .WithMany("Versions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("IAW.Vdf.Persistence.Entities.RuleEntity", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
